# Generated by Django 5.2.8 on 2026-02-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_additionalcharge_booking_alter_booking_guest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Confirmed', 'Confirmed'), ('Checked-In', 'Checked-In'), ('Checked-Out', 'Checked-Out'), ('No-Show', 'No-Show'), ('Cancelled', 'Cancelled')], db_index=True, default='Confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Reserved'), ('Occupied', 'Checked-In'), ('Maintenance', 'Maintenance')], db_index=True, default='Available', max_length=20),
        ),
    ]
