# Generated by Django 5.2.8 on 2026-02-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_booking_check_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_guests',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Payment', 'Payment'), ('Refund', 'Refund'), ('Discount', 'Discount'), ('Adjustment', 'Adjustment')], default='Payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Family', 'Family')], max_length=20),
        ),
    ]
