# Generated by Django 5.2.8 on 2026-02-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_booking_number_of_guests_alter_payment_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_permanently_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_permanently_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='is_permanently_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_permanently_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='is_permanently_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
